[metadata]
name = 'lime-stable'
version = '1.0.7'

[colors] #Default theme
default.bg = '#FFFFFF'
default.fg = '#000000'
default.cont_band = '#8c564b'
default.line_band = '#b5bd61'
default.color_cycle = ['#279e68', '#d62728', '#aa40fc', '#8c564b',  '#e377c2', '#7f7f7f',
                       '#b5bd61', '#17becf', '#1f77b4', '#ff7f0e']
default.match_line = '#b5bd61'
default.peak = '#aa40fc'
default.trough = '#7f7f7f'
default.profile = '#1f77b4'
default.cont = '#ff7f0e'
default.error = '#FF0000'
default.mask_map = 'viridis'
default.comps_map = 'Dark2'
default.mask_marker = '#FF0000'
default.inspection_positive = '#FFFFFF'
default.inspection_negative = '#ff796c' # 'xkcd:salmon'
default.fade_fg = "#CCCCCC"

default.single_width = '1'
default.comp_width = '0.75'
default.err_width = '2'
default.cont_width = '0.5'
default.spectrum_width = '0.75'
default.textsize_notes = 4

#Dark theme
dark.bg = "#2B2B2B"
dark.fg = "#CCCCCC"
dark.cont_band = '#e7298a'
dark.line_band = '#8fff9f'
dark.color_cycle = ['#66c2a5', '#fc8d62', '#e68ac3', '#a6d854',  '#ffd92f', '#e5c494',
                       '#8dcbe2', '#e7298a', '#332288', '#88ccee']
dark.match_line = '#8fff9f'
dark.peak = '#aa40fc'
dark.trough = '#7f7f7f'
dark.profile = '#ddcc77'
dark.cont = "#CCCCCC"
dark.error = '#FF0000'
dark.mask_map = 'viridis'
dark.comps_map = 'PuRd'
dark.mask_marker = '#FF0000'
dark.inspection_positive = "#2B2B2B"
dark.inspection_negative = '#840000'
dark.fade_fg = "#73879B"

dark.single_width = '2'
dark.comp_width = '1.5'
dark.err_width = '3'
dark.cont_width = '0.5'
dark.spectrum_width = '0.75'
dark.textsize_notes = 4

[matplotlib]
default."figure.dpi" = 200
default."figure.figsize" = [4.85, 3]
default."axes.titlesize" = 9
default."axes.labelsize" = 9
default."legend.fontsize" = 7
default."xtick.labelsize" = 8
default."ytick.labelsize" = 8
default."font.size" = 5

#default."figure.dpi" = 150
#default."figure.figsize" = [8, 5]
#default."axes.titlesize" = 14
#default."axes.labelsize" = 14
#default."legend.fontsize" = 12
#default."xtick.labelsize" = 13
#default."ytick.labelsize" = 13

high_res."figure.dpi" = 300
high_res."figure.figsize" = [11, 6]
high_res."axes.titlesize" = 14
high_res."axes.labelsize" = 14
high_res."legend.fontsize" = 12
high_res."xtick.labelsize" = 12
high_res."ytick.labelsize" = 12

dark."figure.facecolor" = "#2B2B2B"
dark."axes.facecolor" = "#2B2B2B"
dark."axes.edgecolor" = "#CCCCCC"
dark."axes.labelcolor" = "#CCCCCC"
dark."xtick.labelcolor" = "#CCCCCC"
dark."ytick.labelcolor" = "#CCCCCC"
dark.'xtick.color'= "#CCCCCC"
dark.'ytick.color'= "#CCCCCC"
dark."text.color" = "#CCCCCC"
dark."legend.edgecolor" = "inherit"
dark."legend.facecolor" = "inherit"

# Bands plot
bands."axes.labelsize" = 8
bands."legend.fontsize" = 5

# Grid plot
grid."axes.titlesize" = 6
grid."axes.titlepad" = 1

# Cube
cube."legend.fontsize" = 5
cube."axes.titlesize" = 6
cube."axes.labelsize" = 6
cube."xtick.labelsize" = 4
cube."ytick.labelsize" = 4


# Cube interactive
cube_interactive.'figure.figsize' = [6.85, 3]
cube_interactive.'axes.titlesize' = 6
cube_interactive.'legend.fontsize' = 6
cube_interactive.'axes.labelsize' = 6
cube_interactive.'xtick.labelsize' = 4
cube_interactive.'ytick.labelsize' = 4
cube_interactive."contour.linewidth" = 0.75
cube_interactive."axes.labelpad" = 1

[linear]
model1D_coeffs = [ 0.75751557,  0.19095596, -1.40579224, -3.62143375, -3.82188512,
                   2.73795767,  6.20858925,  2.7996081 , -3.85524236, -3.60008251,
                   -1.38897289,  0.17660748,  0.72813356]
model1D_intercept = [-5.22250829]

model2D_coeffs = [0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
                 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
                 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
                 0.00000000e+00, -2.65882835e-02, -1.75093575e-02,  9.07892609e-03,
                -6.48494721e-03, -3.17762413e-02,  1.81578522e-02,  2.63288857e-01,
                -3.24247360e-03, -7.52253876e-02, -1.10244102e-02,  5.18795776e-03,
                -1.10244102e-02, -1.68608627e-02, -2.91822624e-02, -1.29698944e-02,
                -3.89096832e-03, -1.94548416e-02, -8.43043137e-02,  3.69641991e-02,
                 2.28918636e-01,  8.49528084e-02, -5.05825882e-02, -2.65882835e-02,
                -5.83645248e-03, -2.46427994e-02, -2.07518311e-02, -3.24247360e-02,
                 3.89096832e-03, -1.29698944e-03, -2.78852730e-02, -6.35524826e-02,
                 9.40317345e-02,  2.14651752e-01,  1.09595608e-01, -8.81952820e-02,
                -4.28006516e-02, -5.83645248e-03, -1.94548416e-02, -2.98307571e-02,
                -4.28006516e-02, -3.89096832e-03, -3.24247360e-03, -4.08551674e-02,
                -6.93889351e-02,  1.76390564e-01,  2.54209930e-01,  1.47208302e-01,
                -9.59772186e-02, -4.79886093e-02, -1.03759155e-02, -2.78852730e-02,
                -4.47461357e-02, -5.05825882e-02, -1.16729050e-02, -2.85337677e-02,
                -6.09585037e-02, -8.17103348e-02,  1.14135071e-01,  1.99087879e-01,
                 1.07650124e-01, -7.65223770e-02, -7.06859245e-02, -1.68608627e-02,
                -4.40976410e-02, -6.03100090e-02, -6.67949562e-02, -2.98307571e-02,
                -2.91822624e-02, -8.68982926e-02, -9.40317345e-02, -3.10628971e-01,
                 3.33326286e-01, -3.20356392e-01, -8.23588295e-02, -8.49528084e-02,
                -2.07518311e-02, -7.71708717e-02, -7.00374298e-02, -9.66257134e-02,
                -4.28006516e-02, -3.69641991e-02, -9.72742081e-02, -1.03110661e-01,
                -3.24247360e-03,  3.40459728e-01, -9.72742081e-03, -1.01165176e-01,
                -7.78193665e-02, -6.48494721e-02, -5.25280724e-02, -5.12310829e-02,
                -7.26314087e-02, -6.80919457e-02, -9.92196922e-02, -1.17377544e-01,
                -6.87404404e-02,  2.14003258e-02,  2.47724983e-01,  9.72742081e-02,
                -5.57705460e-02, -9.79227028e-02, -7.97648506e-02, -7.00374298e-02,
                -5.83645248e-02, -2.59397888e-02, -6.67949562e-02, -9.59772186e-02,
                -9.01407662e-02, -3.89096832e-02,  1.17377544e-01,  2.10112289e-01,
                 6.22554932e-02, -5.51220512e-02, -1.60178196e-01, -1.00516682e-01,
                -7.19829140e-02, -9.27347450e-02, -5.90130196e-02, -1.01813671e-01,
                -1.32292923e-01, -1.29698944e-01, -3.63157044e-02,  6.09585037e-02,
                 2.34755089e-01,  6.03100090e-02, -8.81952820e-02, -1.21917007e-01,
                -1.04407650e-01, -1.45262817e-01, -1.34886902e-01, -9.14377556e-02,
                -7.45768929e-02, -1.06353134e-01, -7.78193665e-02, -9.98681870e-02,
                 9.53287239e-02,  2.67828320e-01,  9.59772186e-02, -5.25280724e-02,
                -1.56287228e-01, -1.98439384e-01, -1.35535397e-01, -1.08947113e-01,
                -9.07892609e-02, -2.05572826e-01, -1.27104965e-01, -8.75467873e-02,
                -2.72367783e-02,  6.61464615e-02,  2.19191216e-01,  8.75467873e-02,
                -3.63157044e-02, -1.55638733e-01, -1.51747765e-01, -8.30073242e-02,
                -1.47856796e-01, -1.43965828e-01, -1.26456471e-01, -1.63420670e-01,
                -2.19839710e-01, -4.47461357e-02,  8.43043137e-03,  1.58881207e-01,
                 4.40976410e-02, -6.03100090e-02, -1.41371849e-01, -1.98439384e-01,
                -1.61475185e-01, -1.61475185e-01, -2.22433689e-01, -1.56287228e-01,
                -1.20620018e-01, -1.97790890e-01, -9.40317345e-02,  5.57705460e-02,
                 1.95845406e-01,  6.42009773e-02, -1.19323029e-01, -1.20620018e-01,
                -1.05704639e-01, -1.99087879e-01, -1.92602932e-01, -1.95196911e-01,
                -1.77039059e-01, -2.78852730e-01, -6.22554932e-02, -8.23588295e-02,
                 8.43043137e-03,  2.06221321e-01, -3.24247360e-03, -9.20862503e-02,
                -1.47208302e-01, -5.12310829e-02, -1.86117985e-01, -1.42020344e-01,
                -1.11541092e-01, -1.93899921e-01, -1.24510986e-01, -1.71851101e-01,
                -1.29050449e-01,  4.15036621e-02,  2.05572826e-01,  1.81578522e-02,
                -1.03759155e-01, -1.30995934e-01, -8.62497978e-02, -1.05056145e-01,
                -2.08815300e-01, -1.07650124e-01, -1.09595608e-01, -1.16729050e-01,
                -1.48505291e-01, -9.27995945e-01, -2.01033363e-02,  2.16597237e-01,
                -1.81578522e-02, -1.02591865e+00, -1.65366154e-01, -2.59397888e-01,
                -1.52396259e-01, -3.17762413e-02, -1.04407650e-01, -7.52253876e-02,
                -1.30347439e-01, -1.13486576e-01,  7.06859245e-02,  3.63157044e-02,
                 2.17245731e-01,  7.13344193e-03,  6.22554932e-02, -1.63420670e-01,
                -2.07518311e-01, -1.60826691e-01, -2.21785194e-01, -1.80281532e-01,
                -1.25807976e-01, -1.15432060e-01, -7.71708717e-02,  3.69641991e-02,
                -2.59397888e-03,  2.15948742e-01,  2.85337677e-02,  7.19829140e-02,
                -1.40074860e-01, -1.56935722e-01, -1.29698944e-01, -1.45911312e-01,
                -7.97648506e-02, -1.50450775e-01, -8.81952820e-02, -6.16069985e-02,
                 2.33458099e-02,  3.11277466e-02,  2.13354763e-01,  3.04792519e-02,
                -1.68608627e-02, -1.11541092e-01, -1.36832386e-01, -1.15432060e-01,
                -7.71708717e-02, -1.39426365e-01, -4.79886093e-02, -8.43043137e-02,
                -1.34238407e-01,  1.68608627e-02,  5.90130196e-02,  2.13354763e-01,
                 2.07518311e-02,  4.86371040e-02, -7.26314087e-02, -8.43043137e-02,
                -1.42668839e-01, -1.09595608e-01, -2.72367783e-02, -6.87404404e-02,
                -7.19829140e-02, -5.18795776e-03, -1.94548416e-02, -6.48494721e-03,
                 2.12706268e-01,  9.72742081e-03, -1.75093575e-02, -7.26314087e-02,
                -8.94922714e-02, -9.85711975e-02, -9.14377556e-02, -1.12189587e-01,
                -5.64190407e-02, -4.86371040e-02, -4.47461357e-02, -2.01033363e-02,
                 5.90130196e-02,  2.11409279e-01,  9.07892609e-03, -2.20488205e-02,
                -7.71708717e-02, -3.04792519e-02, -5.64190407e-02,  1.10244102e-02,
                 2.85337677e-02, -1.62123680e-02, -4.53946304e-03, -4.28006516e-02,
                 1.94548416e-02,  4.02066727e-02,  2.11409279e-01,  5.64190407e-02,
                -1.75093575e-02, -1.68608627e-02, -2.91822624e-02,  1.55638733e-02,
                -6.67949562e-02, -4.34491463e-02,  3.17762413e-02, -2.65882835e-02,
                -2.72367783e-02, -1.88063469e-02,  5.70675354e-02,  2.11409279e-01,
                 6.61464615e-02,  2.52912941e-02, -3.56672096e-02,  3.95581780e-02,
                 4.08551674e-02, -6.48494721e-04,  7.78193665e-02,  2.85337677e-02,
                 3.24247360e-03, -3.50187149e-01,  2.72367783e-02,  2.20488205e-02,
                 2.11409279e-01,  3.37217255e-02, -4.53946304e-03, -3.04792519e-01,
                -2.52912941e-02,  3.37217255e-02,  6.67949562e-02,  6.42009773e-02,
                 2.20488205e-02,  1.94548416e-02, -2.85337677e-02, -2.65882835e-02,
                 3.95581780e-02,  2.11409279e-01,  1.16729050e-02,  2.33458099e-02,
                -1.49153786e-02,  5.18795776e-03,  1.94548416e-02,  1.94548416e-03,
                 6.07510527e-16,  3.37217255e-02,  9.07892609e-03,  6.48494721e-02,
                -5.51220512e-02,  2.20488205e-02,  2.11409279e-01,  3.37217255e-02,
                -9.07892609e-03,  4.21521568e-02, -4.39377759e-16,  3.82611885e-02,
                 2.39943047e-02,  3.95581780e-02,  3.89096832e-02, -1.23213997e-02,
                -1.68608627e-02, -5.77160301e-02,  6.93889351e-02,  2.10760784e-01,
                 6.74434509e-02, -4.53946304e-03, -1.36183891e-02,  2.01033363e-02,
                 1.49153786e-02,  4.08551674e-02,  3.82611885e-02,  6.42009773e-02,
                 2.46427994e-02, -5.70675354e-02, -5.18795776e-02,  6.35524826e-02,
                 2.10112289e-01,  4.86371040e-02, -6.42009773e-02, -4.79886093e-02,
                -1.94548416e-03,  3.30732307e-02,  4.28006516e-02,  4.47461357e-02,
                 1.05704639e-01, -2.06221321e-01, -9.53287239e-02, -1.25159481e-01,
                 8.99462177e-01,  2.10112289e-01,  1.16015706e+00, -8.68982926e-02,
                -7.65223770e-02, -2.31512615e-01,  8.56013031e-02,  7.19829140e-02,
                 1.14783566e-01, -4.60431252e-02,  1.41371849e-01,  2.21136700e-01,
                 2.05572826e-01,  4.99989430e-01,  2.09463795e-01,  4.96098461e-01,
                 2.12706268e-01,  1.83524006e-01,  1.78984543e-01, -5.38250618e-02,
                 1.49802280e-01]
model2D_intercept = [-10.25690062]
box_width = 13

#cube_interactive.'figure.figsize' = [16, 8]
#cube_interactive.'axes.titlesize' = 12
#cube_interactive.'legend.fontsize' = 12
#cube_interactive.'axes.labelsize' = 12
#cube_interactive.'xtick.labelsize' = 10
#cube_interactive.'ytick.labelsize' = 10

